INSERT INTO books(author, title,year,language,price,copies)	VALUES('3','Poema de Gilgamesh','100','EN','34','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('4','Libro de Job (de la Biblia)','100','EN','45','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('5','Las mil y una noches','700','EN','77','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('6','Saga de Njál','800','EN','48','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('7','Todo se desmorona','1958','EN','34','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('8','Cuentos infantiles','1835','EN','45','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('9','Divina comedia','1265','ES','77','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('10','Orgullo y prejuicio','1813','EN','48','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('11','Papá Goriot','1835','EN','34','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('12','Molloy, Malone muere, El Innombrable, una trilogía','1951','EN','45','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('13','Decamerón','1349','EN','77','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('14','Ficciones','1944','RU','34','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('15','Cumbres Borrascosas','1847','EN','45','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('16','El extranjero','1942','EN','77','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('17','Poemas','1952','EN','34','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('18','Viaje al fin de la noche','1932','EN','45','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('19','Don Quijote de la Mancha','1605','EN','77','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('20','Los cuentos de Canterbury','1400','EN','34','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('21','Relatos cortos','1886','EN','45','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('22','Nostromo','1904','EN','77','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('23','Grandes Esperanzas','1861','EN','48','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('24','Jacques el fatalista','1796','EN','15','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('25','Berlin Alexanderplatz','1929','ES','12','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('26','Crimen y castigo','1866','EN','34','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('27','El idiota','1869','EN','45','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('28','Los endemoniados','1872','EN','77','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('29','Los hermanos Karamazov','1880','ES','48','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('30','Middlemarch','1871','EN','34','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('31','El hombre invisible','1952','EN','45','7');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('32','Medea','431','ES','77','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('33','¡Absalom, Absalom!','1936','EN','48','7');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('34','El ruido y la furia','1929','EN','34','7');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('35','Madame Bovary','1857','EN','45','7');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('36','La educación sentimental','1869','EN','77','7');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('37','Romancero gitano','1928','EN','34','7');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('38','Cien años de soledad','1967','EN','45','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('39','El amor en los tiempos del cólera','1985','ES','77','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('40','Fausto','1832','EN','34','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('41','Almas muertas','1842','EN','45','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('42','El tambor de hojalata','1959','ES','77','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('43','Gran Sertón: Veredas','1956','EN','34','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('44','Hambre','1890','EN','45','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('45','El viejo y el mar','1952','EN','77','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('46','Ilíada','850','ES','48','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('47','Odisea','300','EN','15','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('48','Casa de muñecas','1879','EN','12','7');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('49','Ulises','1922','ES','34','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('50','Relatos cortos','1924','EN','45','7');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('51','El proceso','1925','EN','77','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('52','El castillo','1926','PL','48','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('53','Shakuntala','400','EN','34','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('54','El sonido de la montaña','1954','EN','45','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('55','Zorba, el griego','1946','MX','77','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('56','Hijos y amantes','1913','EN','48','7');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('57','Gente independiente','1934','EN','34','7');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('58','Poemas','1818','EN','45','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('59','El cuaderno dorado','1962','EN','77','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('60','Pippi Calzaslargas','1945','EN','34','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('61','Diario de un loco','1918','EN','45','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('62','Hijos de nuestro barrio','1959','TU','77','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('63','Los Buddenbrook','1901','EN','34','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('64','La montaña mágica','1924','EN','45','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('65','Moby-Dick','1851','EN','77','1');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('66','Ensayos','1595','EN','34','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('67','La historia','1974','EN','45','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('68','Beloved','1987','TU','77','3');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('69','Genji Monogatari','1100','EN','48','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('70','El hombre sin atributos','1930','EN','15','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('71','Lolita','1955','EN','12','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('72','1984','1949','EN','34','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('73','Las metamorfosis','100','TU','45','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('74','Libro del desasosiego','1928','EN','77','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('75','Cuentos','1900','EN','48','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('76','En busca del tiempo perdido','1913','EN','34','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('77','Gargantúa y Pantagruel','1532','ES','45','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('78','Pedro Páramo','1955','EN','77','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('79','Masnavi','1258','EN','48','3');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('80','Hijos de la medianoche','1981','EN','34','77');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('81','Bostan','1257','EN','45','3');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('82','Tiempo de migrar al norte','1966','EN','77','7');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('83','Ensayo sobre la ceguera','1995','EN','34','7');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('84','Hamlet','1603','EN','45','3');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('85','El rey Lear','1608','EN','77','3');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('86','Otelo','1609','EN','34','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('87','Edipo rey','430','EN','45','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('88','Rojo y negro','1830','EN','77','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('89','Vida y opiniones del caballero Tristram Shandy','1760','EN','34','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('90','La conciencia de Zeno','1923','EN','45','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('91','Los viajes de Gulliver','1726','EN','77','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('92','Guerra y paz','1865','EN','48','70');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('93','Ana Karenina','1877','EN','15','250');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('94','La muerte de Iván Ilich','1886','EN','12','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('95','Las aventuras de Huckleberry Finn','1884','EN','10','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('96','Ramayana','300','EN','10','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('97','Eneida','29','EN','14','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('98','Mahabhárata','400','EN','15','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('99','Hojas de hierba','1855','EN','15','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('100','La señora Dalloway','1925','EN','15','20');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('101','Al faro','1927','EN','15','25');
INSERT INTO books(author, title,year,language,price,copies)	VALUES('102','Memorias de Adriano','1951','EN','15','10');

si separo con comas puedo omitir la primera orden (Idealmente hasta 50 valores)
INSERT INTO books(author, title,year,language,price,copies)	
    VALUES('97','Eneida','29','EN','14','20'),
	VALUES('98','Mahabhárata','400','EN','15','20'),
	VALUES('99','Hojas de hierba','1855','EN','15','20'),
    VALUES('100','La señora Dalloway','1925','EN','15','20');
    VALUES('101','Al faro','1927','EN','15','25');
    VALUES('102','Memorias de Adriano','1951','EN','15','10');
